// <auto-generated />
using System;
using CarDepo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDepo.Infrastructure.Migrations
{
    [DbContext(typeof(CarDepoContext))]
    [Migration("20260416105701_Restructure")]
    partial class Restructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("CarDepo.API.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MakeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MakeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 7,
                            KMs = 123,
                            License = "8742-GHX",
                            MakeId = 2,
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 9,
                            KMs = 103,
                            License = "7854-ASD",
                            MakeId = 1,
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 2,
                            KMs = 167,
                            License = "4152-RTE",
                            MakeId = 1,
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 1,
                            KMs = 263,
                            License = "6769-QWT",
                            MakeId = 2,
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 3,
                            KMs = 317,
                            License = "4157-NMD",
                            MakeId = 3,
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 4,
                            KMs = 401,
                            License = "3437-PLO",
                            MakeId = 3,
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 7,
                            ColorId = 5,
                            KMs = 320,
                            License = "6167-AUD",
                            MakeId = 1,
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 8,
                            ColorId = 6,
                            KMs = 115,
                            License = "5124-OIY",
                            MakeId = 2,
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 9,
                            ColorId = 8,
                            KMs = 154,
                            License = "3112-THE",
                            MakeId = 1,
                            OwnerId = 3
                        });
                });

            modelBuilder.Entity("CarDepo.API.Models.CarDriver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarCDId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateDrive")
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverCDId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DriverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarCDId");

                    b.HasIndex("DriverCDId");

                    b.HasIndex("DriverId");

                    b.ToTable("CarConductors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarCDId = 1,
                            DateDrive = new DateOnly(2017, 6, 17),
                            DriverCDId = 3
                        },
                        new
                        {
                            Id = 2,
                            CarCDId = 7,
                            DateDrive = new DateOnly(2021, 8, 4),
                            DriverCDId = 5
                        },
                        new
                        {
                            Id = 3,
                            CarCDId = 5,
                            DateDrive = new DateOnly(2019, 11, 22),
                            DriverCDId = 4
                        },
                        new
                        {
                            Id = 4,
                            CarCDId = 9,
                            DateDrive = new DateOnly(2020, 9, 14),
                            DriverCDId = 2
                        },
                        new
                        {
                            Id = 5,
                            CarCDId = 3,
                            DateDrive = new DateOnly(2022, 3, 22),
                            DriverCDId = 1
                        });
                });

            modelBuilder.Entity("CarDepo.API.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rojo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Azul"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Verde"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Naranja"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amarillo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Celeste"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Purpura"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rosa"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Negro"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Blanco"
                        });
                });

            modelBuilder.Entity("CarDepo.API.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 3,
                            Dni = "78546932G",
                            Name = "Pepino",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Dni = "47456968F",
                            Name = "Lucas",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            Dni = "69321453C",
                            Name = "Mario",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 4,
                            CarId = 1,
                            Dni = "49875214L",
                            Name = "Ana",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 5,
                            CarId = 4,
                            Dni = "45161314N",
                            Name = "Regina",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 6,
                            CarId = 5,
                            Dni = "94563214S",
                            Name = "Maria",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("CarDepo.API.Models.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Payed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("CarDepo.API.Models.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Petroleo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hibrido"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Electrico"
                        });
                });

            modelBuilder.Entity("CarDepo.API.Models.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorsePower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FuelTypeId");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FuelTypeId = 1,
                            HorsePower = 163,
                            Name = "Mercedes-Benz A 200",
                            Price = 25632.21m
                        },
                        new
                        {
                            Id = 2,
                            FuelTypeId = 3,
                            HorsePower = 316,
                            Name = "Volvo V60 2.0 T6",
                            Price = 20545.85m
                        },
                        new
                        {
                            Id = 3,
                            FuelTypeId = 2,
                            HorsePower = 118,
                            Name = "Hyundai I20 1.0 TGDI",
                            Price = 16697.64m
                        });
                });

            modelBuilder.Entity("CarDepo.API.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateEntry")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddr")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEntry = new DateOnly(2007, 3, 14),
                            EmailAddr = "jarvis@company.inc",
                            NIF = "N79652124",
                            Name = "Jarvis INC",
                            PhoneNumber = 965123415
                        },
                        new
                        {
                            Id = 2,
                            DateEntry = new DateOnly(2010, 4, 7),
                            EmailAddr = "donquer@companiamania.sl",
                            NIF = "B12472965",
                            Name = "Donquer SL",
                            PhoneNumber = 658120205
                        },
                        new
                        {
                            Id = 3,
                            DateEntry = new DateOnly(2008, 5, 21),
                            EmailAddr = "luzcar@correo.sa",
                            NIF = "A65212479",
                            Name = "Luzcar SA",
                            PhoneNumber = 912341415
                        },
                        new
                        {
                            Id = 4,
                            DateEntry = new DateOnly(2004, 7, 30),
                            EmailAddr = "cantar@ascancions.cb",
                            NIF = "E12495276",
                            Name = "Cántar CB",
                            PhoneNumber = 718916545
                        });
                });

            modelBuilder.Entity("CarDepo.API.Models.Car", b =>
                {
                    b.HasOne("CarDepo.API.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDepo.API.Models.Make", "Make")
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDepo.API.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Make");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CarDepo.API.Models.CarDriver", b =>
                {
                    b.HasOne("CarDepo.API.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarCDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDepo.API.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverCDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDepo.API.Models.Driver", null)
                        .WithMany("CarConductor")
                        .HasForeignKey("DriverId");

                    b.Navigation("Car");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("CarDepo.API.Models.Driver", b =>
                {
                    b.HasOne("CarDepo.API.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDepo.API.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CarDepo.API.Models.Fine", b =>
                {
                    b.HasOne("CarDepo.API.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDepo.API.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CarDepo.API.Models.Make", b =>
                {
                    b.HasOne("CarDepo.API.Models.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelType");
                });

            modelBuilder.Entity("CarDepo.API.Models.Driver", b =>
                {
                    b.Navigation("CarConductor");
                });
#pragma warning restore 612, 618
        }
    }
}
